# Generated by Django 5.2 on 2025-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('merchant', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('description', models.TextField()),
                ('is_fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
