# Generated by Django 5.2 on 2025-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_is_fraud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10),
        ),
    ]
